version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cx-talk-challenge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  db_test:
    image: postgres:15
    container_name: postgres_db_test
    restart: always
    environment:
      POSTGRES_USER: root_test
      POSTGRES_PASSWORD: root_test
      POSTGRES_DB: cx-talk-challenge-test
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: [ "redis-server", "--requirepass", "root" ]
volumes:
  postgres_data:
  postgres_data_test:
